import style9 from "style9";

export const { ...classes } = style9.create({
  btn: {
    paddingRight: 16,
    paddingLeft: 16,
    borderWidth: "1px",
    borderStyle: "solid",
    borderRadius: "9999px",
    cursor: "pointer",
    transitionDuration: "0.2s",
    transitionProperty: "backgroundColor, boxShadow",
    textDecorationLine: "none",
  },
  btnText: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexGrow: 1,
    textAlign: "center",
    fontWeight: 700,
  },
  btnWidthFull: {
    width: "100%",
  },
  btnSmall: {
    minWidth: 32,
    minHeight: 32,
    fontSize: 14,
    lineHeight: "16px",
  },
  btnMedium: {
    minWidth: 36,
    minHeight: 36,
    fontSize: 15,
    lineHeight: "20px",
  },
  btnLarge: {},
  btnExtraLarge: {},
  btnExtraExtraLarge: {},
  btnDisabled: {
    pointerEvents: "none",
    backgroundColor: "rgba(239, 239, 239, 0.3)",
    color: "rgba(16, 16, 16, 0.3)",
    borderColor: "rgba(118, 118, 118, 0.3)",
  },
  btnPrimary: {
    color: "rgba(255, 255, 255, 1)",
    backgroundColor: "rgba(6, 82, 197, 1.0)",
    borderColor: "rgba(207, 217, 222, 1.0)",
  },
  btnPrimaryHover: {
    color: "rgba(255, 255, 255, 0.85)",
    backgroundColor: "rgba(6, 82, 197, 0.85)",
    borderColor: "rgba(207, 217, 222, 0.85)",
  },
  btnSecondary: {},
  btnSecondaryHover: {},
  btnSuccess: {},
  btnSuccessHover: {},
  btnDanger: {},
  btnDangerHover: {},
  btnWarning: {},
  btnWarningHover: {},
  btnInfo: {},
  btnInfoHover: {},
  btnLight: {},
  btnLightHover: {},
  btnDark: {},
  btnDarkHover: {},
  btnPrimaryOutline: {
    backgroundColor: "rgba(0, 0, 0, 0)",
  },
  btnPrimaryOutlineHover: {
    backgroundColor: "rgba(29, 155, 240, 0.1)",
    borderColor: "rgba(29, 155, 240, 1)",
  },
  btnSecondaryOutline: {},
  btnSecondaryOutlineHover: {},
  btnSuccessOutline: {},
  btnSuccessOutlineHover: {},
  btnDangerOutline: {},
  btnDangerOutlineHover: {},
  btnWarningOutline: {},
  btnWarningOutlineHover: {},
  btnInfoOutline: {},
  btnInfoOutlineHover: {},
  btnLightOutline: {},
  btnLightOutlineHover: {},
  btnDarkOutline: {},
  btnDarkOutlineHover: {},
});
